#!/usr/bin/env python
"""Turn the SPEC §7.2 arm artifacts into `docs/RESULTS.md`.

    python scripts/phase5_report.py --task bfcl_live_simple --out docs/RESULTS.md

Every rate is printed with a Wilson interval, and every arm-vs-arm claim is a
**paired** McNemar test corrected for all pairwise comparisons — the arms run on
the same records, so an unpaired two-proportion test would both discard the
pairing and be less powerful.

CLAUDE.md: never silently cap coverage. If an arm has fewer records than
another, or records were skipped at compile time, this says so in the table
rather than in a footnote nobody reads.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess

from diffgemma_fa.eval.stats import bonferroni, fmt_rate, mcnemar_exact, wilson

#: The order SPEC §7.2 makes its argument in.
ARM_ORDER = [
    ("unconstrained", "sample"),
    ("mask", "sample"),
    ("j2", "sample"),
    ("j1", "sample"),
    ("j0", "map"),
    ("j0", "sample"),
]

ARM_BLURB = {
    ("unconstrained", "sample"): "stock DiffusionGemma, untouched",
    ("mask", "sample"): "naive per-position masking (§2.8's target)",
    ("j2", "sample"): "constrained draw at accepted positions, random elsewhere",
    ("j1", "sample"): "single joint draw, flattened marginals at non-accepted",
    ("j0", "map"): "decoupled emission, constrained MAP",
    ("j0", "sample"): "decoupled emission, joint draw",
}


def load_arms(task: str, artifacts: pathlib.Path) -> dict:
    out = {}
    for variant, emission in ARM_ORDER:
        p = artifacts / f"eval_{task}_{variant}_{emission}.json"
        if p.exists():
            out[(variant, emission)] = json.load(open(p))
    return out


def per_record(arm: dict, field: str) -> dict[str, bool]:
    """`{record_id: bool}` for a per-record boolean column."""
    return {r["id"]: bool(r.get(field, False)) for r in arm["rows"]}


def paired(a: dict, b: dict, field: str) -> tuple[int, int, int]:
    """`(b_count, c_count, n_shared)` over the records both arms ran."""
    x, y = per_record(a, field), per_record(b, field)
    shared = sorted(set(x) & set(y))
    bb = sum(1 for k in shared if x[k] and not y[k])
    cc = sum(1 for k in shared if y[k] and not x[k])
    return bb, cc, len(shared)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--task", default="bfcl_live_simple")
    ap.add_argument("--artifacts", default="artifacts")
    ap.add_argument("--out", default="docs/RESULTS.md")
    args = ap.parse_args()

    arms = load_arms(args.task, pathlib.Path(args.artifacts))
    if not arms:
        raise SystemExit(f"no arm artifacts for task {args.task!r}")

    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                            capture_output=True, text=True).stdout.strip()
    dedicated = subprocess.run(["bash", "-c", "echo ${DGFA_DEDICATED:-unset}"],
                               capture_output=True, text=True).stdout.strip()

    L = []
    w = L.append
    w(f"# Results — SPEC §7.2, task `{args.task}`\n")
    w(f"Generated by `scripts/phase5_report.py` at commit `{commit}`.\n")

    ns = {k: v["n"] for k, v in arms.items()}
    if len(set(ns.values())) > 1:
        w("> **Arms do not share a record count** — "
          + ", ".join(f"`{v}-{e}`={n}" for (v, e), n in ns.items())
          + ". Paired tests below use only the shared records, and the count "
            "is stated per comparison.\n")

    missing = [f"`{v}-{e}`" for v, e in ARM_ORDER if (v, e) not in arms]
    if missing:
        w(f"> **Incomplete table.** Missing arms: {', '.join(missing)}. "
          "They are not omitted for being uninteresting — they have not been "
          "run.\n")

    # -- the table ---------------------------------------------------------
    w("\n## Rates, with 95% Wilson intervals\n")
    w("| arm | n | CS | schema valid | parsed | non-empty | arg acc | exact call |")
    w("|---|---|---|---|---|---|---|---|")
    for key in ARM_ORDER:
        if key not in arms:
            continue
        d = arms[key]
        n = d["n"]
        w(f"| `{key[0]}-{key[1]}` | {n} "
          f"| {fmt_rate(d['cs'], n)} "
          f"| {fmt_rate(d['schema_ok'], n)} "
          f"| {fmt_rate(d['parsed'], n)} "
          f"| {fmt_rate(d['nonempty'], n)} "
          f"| {fmt_rate(d['arg_correct'], d['arg_total'])} "
          f"| {fmt_rate(d['exact_calls'], n)} |")

    w("\n**Read the two leftmost columns together, and neither alone.**\n")
    w("- **CS** is the guarantee the sampler enforces: the emitted *token "
      "sequence* is accepted by the compiled automaton. That automaton carries "
      "SPEC §3.6's `<|channel>NAME\\n<channel|>` header, which is **our** "
      "addition — the stock model has no reason to emit it, so the baseline "
      "arms score near zero here partly for a convention they were never asked "
      "to follow. A 0% → 100% CS jump reported on that basis alone would "
      "overstate the result.")
    w("- **schema valid** asks whether the parsed object validates against the "
      "schema. Header-independent and tokenizer-independent, so it is the "
      "question every arm can be asked fairly, and it is what the benchmark "
      "cares about.")
    w("- **arg acc** is per *argument*, over `arg_total` arguments rather than "
      "over records; **exact call** requires every argument of a call to be "
      "right and is the stricter, more comparable number.")
    w("- SPEC §3.8: CS can be trivially 100% while measuring nothing — a run "
      "emitting `{\"location\":\"\"}` every time scores perfectly. That is why "
      "the content columns are never dropped.\n")

    # -- paired comparisons ------------------------------------------------
    keys = [k for k in ARM_ORDER if k in arms]
    n_comp = len(keys) * (len(keys) - 1) // 2
    for field, label in (("schema_ok", "schema validity"),
                         ("accepted", "constraint satisfaction")):
        w(f"\n## Paired comparisons — {label}\n")
        w(f"Exact McNemar on the discordant records only, Bonferroni-corrected "
          f"for all {n_comp} pairwise comparisons of {len(keys)} arms. `b` is "
          f"records the row arm got right and the column arm did not.\n")
        w("| A | B | b | c | shared n | p (raw) | p (corrected) |")
        w("|---|---|---|---|---|---|---|")
        for i, ka in enumerate(keys):
            for kb in keys[i + 1:]:
                bb, cc, ns_ = paired(arms[ka], arms[kb], field)
                p = mcnemar_exact(bb, cc)
                pc = bonferroni(p, n_comp)
                mark = " **" if pc < 0.05 else " "
                w(f"| `{ka[0]}-{ka[1]}` | `{kb[0]}-{kb[1]}` | {bb} | {cc} "
                  f"| {ns_} | {p:.3g} |{mark}{pc:.3g}{mark.strip()} |")

    # -- the grammar result ------------------------------------------------
    import glob
    exps = {}
    for f in sorted(glob.glob(str(pathlib.Path(args.artifacts) / "exp_*.json"))):
        exps[pathlib.Path(f).stem[4:]] = json.load(open(f))
    if exps:
        w("\n## The grammar fix, and the ablation that explains it\n")
        w("The compiled grammar admitted **none** of the 130 outputs the "
          "unconstrained arm produced: it forbids the model's newline+indent "
          "separators, so at every value boundary the renormalised draw "
          "extends the value instead of closing it (`600` -> `6000`, `USA` -> "
          "`\"USA1  \"`). 58% of the measured accuracy gap was that. "
          "`--whitespace pretty` admits `( |\\n {0,6})?`, the separators the "
          "model actually uses.\n")
        w("| config | n | CS | schema valid | arg acc | exact call | Z==0 |")
        w("|---|---|---|---|---|---|---|")
        for tag in sorted(exps):
            d = exps[tag]
            n = d["n"]
            w(f"| `{tag}` | {n} | {fmt_rate(d['cs'], n)} "
              f"| {fmt_rate(d['schema_ok'], n)} "
              f"| {fmt_rate(d['arg_correct'], d['arg_total'])} "
              f"| {fmt_rate(d['exact_calls'], n)} "
              f"| {d.get('zero_partition', '-')} |")
        w("\n**The whitespace carries all of it.** On MAP emission at n=130, "
          "each component of the bundle alone: fence 0.328, case-insensitive "
          "enums 0.335, whitespace **0.622**, all three 0.628 — against a "
          "stock-grammar baseline of 0.328 and an unconstrained model at "
          "0.641. The fence was motivated by a string-level proxy (verbatim "
          "acceptance of a whole unconstrained output: 0/130 without it, "
          "74/130 with) that turned out not to predict the thing it was used "
          "to predict — mid-generation only the separators matter.\n")
        w("**float32 is not an option on the sample path.** It was briefly "
          "made the default on a toy-scale check (`L=4`, `|S|<=8`); at "
          "`L=256` on this grammar it drives the `Z == 0` detector on 70/130 "
          "and 55/130 records across two seeds, against 0/130 in float64. The "
          "guarantee held — those records fail loudly rather than emitting "
          "garbage — but the kernel is spuriously infeasible on half the "
          "corpus. The `exp_e5_*` artifacts are that measurement; the "
          "`exp_f64_*` ones are the float64 reruns.\n")

    # -- coverage ----------------------------------------------------------
    w("\n## Coverage and caveats\n")
    for key in keys:
        d = arms[key]
        skipped = d.get("skipped_by_reason") or {}
        w(f"- `{key[0]}-{key[1]}`: n={d['n']} of "
          f"{d.get('records_available', '?')} available; "
          f"skipped at compile time: {skipped or 'none'}; "
          f"seed={d.get('seed')}; entropy_bound={d.get('entropy_bound')}; "
          f"nonempty_strings={d.get('nonempty_strings')}; "
          f"{d.get('elapsed_seconds')} s.")
    w("")
    w(f"- **Task**: `{args.task}`. This is one split, not all of BFCL. Records "
      "with more than one candidate function are excluded — the grammar is "
      "compiled from a single schema.")
    w("- `--nonempty` gives every required string `minLength: 1`. Measured "
      "cost: exactly two BFCL-Live ground truths are required strings the "
      "benchmark accepts as empty (`live_multiple_507-149-4`, "
      "`live_multiple_834-178-9`), and they are unanswerable under this flag.")
    w(f"- **`DGFA_DEDICATED={dedicated}`.** If 0, JAX preallocation is off and "
      "the GPU is shared: any latency number measured here is pessimistic and "
      "not publishable (CLAUDE.md). The columns above are accuracy, not "
      "latency, and are unaffected.")
    w("- **Only 130 of the 258 single-function records in this split were "
      "evaluated** — the first 130 by id. A prefix is not a random sample "
      "(BFCL ids cluster by schema family), so every number here is a "
      "first-half claim.")
    w("- Every arm is **one generation at one seed**. The measured seed spread "
      "for an identical config at n=30 is 0.412 / 0.412 / 0.314, so treat "
      "differences under ~0.1 at that size as noise.")
    w("- **SPEC §7.3's overhead table is not here and has never been "
      "measured.** That is the paper's headline performance claim (+4%), and "
      "it now has to be measured against a bandwidth-bound `log_matmul` "
      "rather than the GEMM the design assumed — the honest number may be "
      "materially worse.")
    w("- Missing from this table entirely: Spider, and five of the six "
      "datasets SPEC §7.1 lists. Not run. SPEC §3.8's refusal-branch union is "
      "unimplemented, so BFCL's 1,124 irrelevance records have no path to a "
      "score.")

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out} ({len(keys)} arms)")


if __name__ == "__main__":
    main()
